auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:categories/:title 

title: Blog of Miantang
url: http://miantang.github.io/blog
feed: /atom.xml
author_info: <a href="http://miantang.github.io/blog">Miantang</a>

author : 
  name : Miantang
  email : antisaber@gmail.com
  github : Miantang
  twitter : mt2333
  weibo : mt233

  baseurl : /
  linkurl : http://ppii.in

